package br.ifce.ppd.view;

/**
 * Classe: Principal.java
 * View Principal do Chat
 * @author Tiago Malveira
 * 
 */

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

public class Principal extends javax.swing.JFrame {

    public Principal(String nome) {
        initComponents();
        inicializar();
        
        this.nome=nome;
        
        jltSalas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        Vector<String> lista = new Vector<String>();
        lista.add("Sala1");
        lista.add("Sala2");
        insereListaChat(lista);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jbtEntrarSala = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jltSalas = new javax.swing.JList();
        jtpPainelAbas = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jbtEntrarSala.setText("Entrar na Sala");
        jbtEntrarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEntrarSalaActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jltSalas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbtEntrarSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtEntrarSala))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtpPainelAbas, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jtpPainelAbas, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtEntrarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEntrarSalaActionPerformed
         if (jltSalas.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione um contato!"
                    ,"Aviso",  JOptionPane.WARNING_MESSAGE);
            return;
        }
         
        String salaSelecionada = jltSalas.getSelectedValue().toString(); 
        
        boolean existeAba = false;
        
        if (listaAbas.size()>0){
            existeAba=true;
        }
        
         if (!existeAba){
            Aba2 aba = new Aba2(salaSelecionada);
            jtpPainelAbas.addTab(salaSelecionada,aba);
            listaAbas.add(aba);
        }
        else{
            JOptionPane.showMessageDialog(null, "Já existe uma sala aberta. Para entrar em outra sala, saia da atual!"
                    ,"Aviso",  JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbtEntrarSalaActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtEntrarSala;
    private static javax.swing.JList jltSalas;
    private javax.swing.JTabbedPane jtpPainelAbas;
    // End of variables declaration//GEN-END:variables
 
    private static Vector<Aba2> listaAbas = new  Vector<Aba2>();
    private static DefaultListModel  listModel = new DefaultListModel();    
    private boolean flg_thread=true;
    private String nome;

 
    public static Vector<Aba2> getListaAbas() {
        return listaAbas;
    }
    
    
     /**
    * Insere um nome na lista de login do Chat
    *             
    * @param nome   nome a ser inserido na lista do chat
    * @return       void
    */
    public  void insereListaChat(Vector<String> listaLogin){
        
        for (String s : listaLogin){
            if (idNomeListaChat(s) == -1) {
                listModel.addElement(s);
                jltSalas.setModel(listModel);
            }
        }     
    }  
    
    /**
    * Identifica o id de um nome na lista do chat
    *             
    * @param    nome   nome a ser buscado na lista de login do chat
    * @return   void   indice i do nome da lista, se existir. -1, caso contrário 
    */
    public static int idNomeListaChat(String nome){
        
        for (int i=0; i<listModel.getSize();i++){
            if (listModel.get(i).toString().equals(nome)){
                return i;
            }
        }
        return -1;
    }
    
    
    /**
    * Código para Tratar evento Fechar Janela pelo X 
    *             
    * @return       void
    */
    private void inicializar() {
        addWindowListener(new WindowListener() {

            @Override
            public void windowOpened(WindowEvent we) {
                 //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void windowClosing(WindowEvent we) {
                if (we.getID() == WindowEvent.WINDOW_CLOSING) {
                    flg_thread=false;
                    System.exit(0);
                }
            }

            @Override
            public void windowClosed(WindowEvent we) {
                //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void windowIconified(WindowEvent we) {
                 //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void windowDeiconified(WindowEvent we) {
                //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void windowActivated(WindowEvent we) {
                 //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void windowDeactivated(WindowEvent we) {
                //To change body of generated methods, choose Tools | Templates.
            }      
        });   
    }
}
